name: Deploy into test server

on:
  push:
    branches:
    - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare .ssh dir
        run: mkdir -p .ssh && chmod 700 .ssh
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > .ssh/id_ed25519 && chmod 600 .ssh/id_ed25519
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSHKEY }}
      - name: install packages
        run: yarn install
      - name: build api
        run: yarn api:build
      - name: build
        run: yarn build
      - name: push with scp
        run: scp -r -o StrictHostKeyChecking=no -P $SSH_PORT -i .ssh/id_ed25519 ./dist/. $SSH_USER@$SSH_HOST:$DIR
        env:
          DIR: ${{ secrets.DEST_DIR_TEST }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_PORT: ${{ secrets.SERVER_PORT }}
