name: Test pull request

on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: yarn install
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
